elasticsearchHosts: "http://elasticsearch-master.elastic-system.svc.cluster.local:9200"
elasticsearchUsername: "elastic"
elasticsearchPassword: "yourStrongPassword"

service:
  type: ClusterIP
  port: 5601

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
