replicas: 2
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

elasticsearchHosts: "https://elasticsearch-master:9200"
elasticsearchUsername: "elastic"
elasticsearchPassword: "changeme123"  # Use Secret in production

# Expose via ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: kibana.example.com
      paths:
        - path: /
          pathType: Prefix
tls:
  - hosts:
      - kibana.example.com
    secretName: kibana-tls
