replicas: 1
minimumMasterNodes: 1

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    discovery.type: single-node

secret:
  enabled: true
  password: yourStrongPassword

service:
  type: ClusterIP
  port: 9200

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
