apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apm-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-org>/apm-monitor.git'
    targetRevision: main
    path: apm-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
