replicas: 2
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

apmServer:
  host: "0.0.0.0"
  port: 8200
  secretToken: "changemeapm"  # Use Secret in production

output:
  elasticsearch:
    hosts: ["https://elasticsearch-master:9200"]
    username: "elastic"
    password: "changeme123"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: apm.example.com
      paths:
        - path: /
          pathType: Prefix
tls:
  - hosts:
      - apm.example.com
    secretName: apm-tls
