elasticsearchHosts: "http://elasticsearch-master.elastic-system.svc.cluster.local:9200"
elasticsearchUsername: "elastic"
elasticsearchPassword: "yourStrongPassword"
kibanaHost: "http://kibana-kibana.elastic-system.svc.cluster.local:5601"

replicaCount: 1

service:
  type: ClusterIP
  port: 8200

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    output.elasticsearch:
      hosts: ["http://elasticsearch-master.elastic-system.svc.cluster.local:9200"]
      username: "elastic"
      password: "yourStrongPassword"
    setup.kibana:
      host: "http://kibana-kibana.elastic-system.svc.cluster.local:5601"
